<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-MRVJBNT" failures="0" tests="6" name="com.menumitratCommonAPITestScript.UpdateOrderTestScript" time="1.768" errors="4" timestamp="22 May 2025 18:35:33 GMT">
  <testcase classname="com.menumitratCommonAPITestScript.UpdateOrderTestScript" name="updateOrder" time="0.000">
    <error message="
Method private void com.menumitratCommonAPITestScript.UpdateOrderTestScript.updateOrder(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws com.menumitra.utilityclass.customException requires a @DataProvider named : getUpdateOrderData" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Method private void com.menumitratCommonAPITestScript.UpdateOrderTestScript.updateOrder(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) throws com.menumitra.utilityclass.customException requires a @DataProvider named : getUpdateOrderData
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:263)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:419)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </error>
  </testcase> <!-- updateOrder -->
  <testcase classname="com.menumitratCommonAPITestScript.UpdateOrderTestScript" name="updateCounterOrder" time="0.241"/>
  <testcase classname="com.menumitratCommonAPITestScript.UpdateOrderTestScript" name="updateDriveThroughOrder" time="0.000">
    <error message="com.menumitra.utilityclass.customException: Error while reading positive update drive-through order test scenario data: No positive update drive-through order test cases found in test data" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: com.menumitra.utilityclass.customException: Error while reading positive update drive-through order test scenario data: No positive update drive-through order test cases found in test data
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.menumitra.utilityclass.customException: Error while reading positive update drive-through order test scenario data: No positive update drive-through order test cases found in test data
	at com.menumitratCommonAPITestScript.UpdateOrderTestScript.getUpdateDriveThroughOrderData(UpdateOrderTestScript.java:289)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	... 9 more
]]>
    </error>
  </testcase> <!-- updateDriveThroughOrder -->
  <testcase classname="com.menumitratCommonAPITestScript.UpdateOrderTestScript" name="updateParcelOrder" time="0.268"/>
  <testcase classname="com.menumitratCommonAPITestScript.UpdateOrderTestScript" name="updateDineInOrder" time="1.259">
    <error message="Exception in update Dine-In order test: Status code mismatch - Expected: 200, Actual: 400" type="com.menumitra.utilityclass.customException">
      <![CDATA[com.menumitra.utilityclass.customException: Exception in update Dine-In order test: Status code mismatch - Expected: 200, Actual: 400
	at com.menumitratCommonAPITestScript.UpdateOrderTestScript.updateDineInOrder(UpdateOrderTestScript.java:461)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </error>
  </testcase> <!-- updateDineInOrder -->
  <testcase classname="com.menumitratCommonAPITestScript.UpdateOrderTestScript" name="updateDeliveryOrder" time="0.000">
    <error message="com.menumitra.utilityclass.customException: Error while reading positive update delivery order test scenario data: No positive update delivery order test cases found in test data" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: com.menumitra.utilityclass.customException: Error while reading positive update delivery order test scenario data: No positive update delivery order test cases found in test data
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:163)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.menumitra.utilityclass.customException: Error while reading positive update delivery order test scenario data: No positive update delivery order test cases found in test data
	at com.menumitratCommonAPITestScript.UpdateOrderTestScript.getUpdateDeliveryOrderData(UpdateOrderTestScript.java:203)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:137)
	... 9 more
]]>
    </error>
  </testcase> <!-- updateDeliveryOrder -->
</testsuite> <!-- com.menumitratCommonAPITestScript.UpdateOrderTestScript -->
